### ISSUE TITLE
Adding multiple committee members

### ISSUE THREAD

**Issue by Bjorn48** [SERG-Delft/thesis-template#13]
It seems I am not able to add multiple committee members (for on the abstract page), using the `\committeemember` command, to be added besides the chair and university supervisor. It only renders the last one I define in the PDF. Is there a way to add multiple extra committee members?

**Comment by svenpopping** [comment]
One way to do it is:
`\committeemember{Name 1 \\ & Name 2 \\ & Name 3}`
