### ISSUE TITLE
Move source files to root directory

### ISSUE THREAD

**Issue by TimvdLippe** [SERG-Delft/thesis-template#4]
Currently, the source files reside in `thesis-style` while the generated zip resides in the root folder. However, GitHub allows "Download as zip" (right next to the clone URL). By moving the source files to the root directory, this "Download as zip" will be effectively the same as the binary zip file currently being uploaded. Lastly, the previous distributions can be available as GitHub release (which also supports adding files to a release). 

All in all, it should no longer be necessary to have binary files in this repository and is clearer what the latest version of the thesis template is.

**Comment by Inventitech** [comment]
Agreed.

**Comment by TimvdLippe** [comment]
Awesome @Inventitech ! I have published a release for future reference as well: https://github.com/SERG-Delft/thesis-template/releases/tag/2018.4
